on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:53146
on ln. 41, +5.22
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +7.22
	of handle_http_requests(...)
	| [127.0.0.1:54050] received 'GET /regis'
on ln. 41, +7.54
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +9.55
	of handle_http_requests(...)
	| [127.0.0.1:54054] received 'GET /favic'
on ln. 41, +14.06
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +16.07
	of handle_http_requests(...)
	| [127.0.0.1:54058] received 'GET / HTTP'
on ln. 41, +16.32
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +18.32
	of handle_http_requests(...)
	| [127.0.0.1:54062] received 'GET /favic'
on ln. 41, +47.31
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +49.32
	of handle_http_requests(...)
	| [127.0.0.1:54066] received 'GET / HTTP'
on ln. 41, +49.54
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 156, +51.55
	of handle_http_requests(...)
	| [127.0.0.1:54070] received 'GET /favic'
on ln. 50, +62.45
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +62.46
	of __del__(...)
	| garbage collecting SocketServer instance
