on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:60041
on ln. 41, +4.04
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +6.05
	of handle_http_requests(...)
	| [127.0.0.1:41920] received 'GET /regis'
on ln. 41, +6.46
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +8.47
	of handle_http_requests(...)
	| [127.0.0.1:41924] received 'GET /favic'
on ln. 41, +8.84
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +10.84
	of handle_http_requests(...)
	| [127.0.0.1:41928] received 'POST /regi'
on ln. 41, +10.85
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +12.86
	of handle_http_requests(...)
	| [127.0.0.1:41932] received 'GET / HTTP'
on ln. 41, +13.1
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +15.1
	of handle_http_requests(...)
	| [127.0.0.1:41936] received 'GET /favic'
on ln. 41, +36.2
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +38.2
	of handle_http_requests(...)
	| [127.0.0.1:41940] received 'GET / HTTP'
on ln. 41, +38.49
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 168, +40.49
	of handle_http_requests(...)
	| [127.0.0.1:41944] received 'GET /favic'
on ln. 50, +42.94
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +42.96
	of __del__(...)
	| garbage collecting SocketServer instance
