on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +0.38
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +1.38
	of handle_http_requests(...)
	| [192.168.0.8:53288] received 'GET /get_r'
on ln. 184, +1.38
	of handle_http_requests(...)
	| [192.168.0.8:53288] abruptly closed
on ln. 41, +1.39
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +2.38
	of handle_http_requests(...)
	| [192.168.0.8:53290] received 'GET /get_r'
on ln. 184, +2.38
	of handle_http_requests(...)
	| [192.168.0.8:53290] abruptly closed
on ln. 41, +2.39
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +2.93
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +3.38
	of handle_http_requests(...)
	| [192.168.0.8:53298] received 'GET /get_r'
on ln. 184, +3.38
	of handle_http_requests(...)
	| [192.168.0.8:53298] abruptly closed
on ln. 41, +3.38
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +3.93
	of handle_http_requests(...)
	| [192.168.0.8:53300] received 'GET / HTTP'
on ln. 178, +3.98
	of handle_http_requests(...)
	| [192.168.0.8:53306] received 'GET /get_r'
on ln. 184, +3.98
	of handle_http_requests(...)
	| [192.168.0.8:53306] abruptly closed
on ln. 41, +4.02
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +5.03
	of handle_http_requests(...)
	| [192.168.0.8:53308] received 'GET /get_r'
on ln. 41, +5.21
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.21
	of handle_http_requests(...)
	| [192.168.0.8:53312] received 'GET /favic'
on ln. 41, +21.51
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +22.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +22.51
	of handle_http_requests(...)
	| [192.168.0.8:53314] received 'GET /favic'
on ln. 178, +23.34
	of handle_http_requests(...)
	| [192.168.0.8:53316] received 'GET /get_r'
on ln. 184, +23.34
	of handle_http_requests(...)
	| [192.168.0.8:53316] abruptly closed
on ln. 41, +23.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +24.33
	of handle_http_requests(...)
	| [192.168.0.8:53322] received 'GET /get_r'
on ln. 184, +24.33
	of handle_http_requests(...)
	| [192.168.0.8:53322] abruptly closed
on ln. 41, +24.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +25.33
	of handle_http_requests(...)
	| [192.168.0.8:53324] received 'GET /get_r'
on ln. 184, +25.33
	of handle_http_requests(...)
	| [192.168.0.8:53324] abruptly closed
on ln. 41, +25.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +26.33
	of handle_http_requests(...)
	| [192.168.0.8:53326] received 'GET /get_r'
on ln. 184, +26.33
	of handle_http_requests(...)
	| [192.168.0.8:53326] abruptly closed
on ln. 41, +26.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +27.34
	of handle_http_requests(...)
	| [192.168.0.8:53328] received 'GET /get_r'
on ln. 184, +27.34
	of handle_http_requests(...)
	| [192.168.0.8:53328] abruptly closed
on ln. 41, +27.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +28.33
	of handle_http_requests(...)
	| [192.168.0.8:53330] received 'GET /get_r'
on ln. 184, +28.34
	of handle_http_requests(...)
	| [192.168.0.8:53330] abruptly closed
on ln. 41, +28.34
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 41, +29.29
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +29.33
	of handle_http_requests(...)
	| [192.168.0.8:53332] received 'GET /get_r'
on ln. 184, +29.33
	of handle_http_requests(...)
	| [192.168.0.8:53332] abruptly closed
on ln. 41, +29.33
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +30.3
	of handle_http_requests(...)
	| [192.168.0.8:53334] received 'GET /?erro'
on ln. 178, +30.34
	of handle_http_requests(...)
	| [192.168.0.8:53336] received 'GET /get_r'
on ln. 41, +30.42
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +31.43
	of handle_http_requests(...)
	| [192.168.0.8:53338] received 'GET /get_r'
on ln. 41, +31.71
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +32.71
	of handle_http_requests(...)
	| [192.168.0.8:53340] received 'GET /favic'
on ln. 41, +50.66
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +51.67
	of handle_http_requests(...)
	| [192.168.0.8:53344] received 'GET /favic'
on ln. 41, +54.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +55.85
	of handle_http_requests(...)
	| [192.168.0.8:53348] received 'GET / HTTP'
on ln. 41, +55.94
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +56.94
	of handle_http_requests(...)
	| [192.168.0.8:53350] received 'GET /get_r'
on ln. 41, +57.21
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +58.21
	of handle_http_requests(...)
	| [192.168.0.8:53352] received 'GET /favic'
on ln. 50, +62.39
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +62.4
	of __del__(...)
	| garbage collecting SocketServer instance
