on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +5.06
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.07
	of handle_http_requests(...)
	| [192.168.0.8:49144] received 'GET / HTTP'
on ln. 50, +8.41
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +8.42
	of __del__(...)
	| garbage collecting SocketServer instance
